### ISSUE TITLE
Errors when using plugin

### ISSUE THREAD

**Issue by HEmile** [hadynz/obsidian-sidekick#1]
Hi, loving the idea of this plugin! I don't see anywhere in my vault where it is working yet though. It is giving me several TypeErrors too:

![image](https://user-images.githubusercontent.com/1289165/153409595-a91728c1-21a5-429b-9188-e293fe6a160d.png)

**Comment by Quorafind** [comment]
![image](https://user-images.githubusercontent.com/13215013/153419303-0cb016e1-30ca-4373-8b0e-6eeb8730f5d5.png)

Same here

**Comment by simontang** [comment]
<img width="450" alt="image" src="https://user-images.githubusercontent.com/1438670/153534576-1d1a231c-5b43-453b-a8f0-91d5c120249b.png">
just click the highlight word

**Comment by hadynz** [comment]
Thanks all for sharing the errors you were getting.

The plugin indexes any `aliases` defined in frontmatter to use as keyword of connections. Aliases can be defined as strings, arrays or even be malformed. This plugin didn't cater for that.

[1.0.1][1] should resolve this. Please give it a go and let me know if it has resolved this issue.

[1]: https://github.com/hadynz/obsidian-sidekick/releases/tag/1.0.1

**Comment by Quorafind** [comment]
![image](https://user-images.githubusercontent.com/13215013/153711742-ef86fa2e-6708-4f75-a03c-831bee3f08fd.png)

Is this related to the problem also? It occurs in 1.0.1

**Comment by hadynz** [comment]
I've added more logging for the specific error that you are getting.

Can you update to [1.0.2][1] and share:
* The more detailed console error message
* The frontmatter of the given page in error if you can infer it from the error message 

[1]: https://github.com/hadynz/obsidian-sidekick/releases/tag/1.0.2

**Comment by Quorafind** [comment]
First: 

![image](https://user-images.githubusercontent.com/13215013/153712664-5b79a688-8c6b-4562-bbe9-25ee2c7953db.png)

![image](https://user-images.githubusercontent.com/13215013/153712682-acd1d971-b272-4387-ae4a-12f7e3c371c2.png)

```
---
uid: 202112311951
tags:
  - writings
  - idea
aliases:
  - 年终总结
  - 总结
  - 2020
---
```

---

Second:

![image](https://user-images.githubusercontent.com/13215013/153712755-40d16a46-25d8-4f91-a913-d05843f263fe.png)

![image](https://user-images.githubusercontent.com/13215013/153712778-875a40ed-e086-42fb-920b-a59e06f561ff.png)


```
---
title: Awesome-academics
uid: 202009071818
tags:
  - pkm
  - Extraction
aliases: 
  - 学术
  - 
date updated: '2020-12-17T11:02:33+08:00'

---
```

---

Third:

![image](https://user-images.githubusercontent.com/13215013/153712867-66e5662d-8564-43a5-bf72-504be2881103.png)

```
---
uid: 202101152149
tags:
  - writings
  - idea
aliases:
  - 年终总结
  - 总结
  - 2020
date updated: '2021-02-01T14:03:33+08:00'
---
```

**Comment by Quorafind** [comment]
Hope this help!

**Comment by hadynz** [comment]
This is great. Thank you so much. 

The issue is that you have types of aliases that I didn't cater for - (a) numbers and (b) empty line (or bulls)

The fix is straight forward. Will do it straight after breakfast 😅

**Comment by hadynz** [comment]
Alright, can you give [1.0.3][1] a go. It should handle the aliases in the examples you've shared.

[1]: https://github.com/hadynz/obsidian-sidekick/releases/tag/1.0.3

**Comment by Quorafind** [comment]
![image](https://user-images.githubusercontent.com/13215013/153734579-35e4a856-454f-4a44-ae42-7f2d2abb058a.png)

![image](https://user-images.githubusercontent.com/13215013/153734619-70984493-9915-467e-bb47-3966d33c3803.png)

![image](https://user-images.githubusercontent.com/13215013/153734623-9f9ba2e8-be4d-49eb-a633-13cb5640d8ba.png)


Seems like another error comes. but the first error is resloved now!

**Comment by hadynz** [comment]
@Quorafind can you try the latest [1.0.4][1] please?

I believe I found the issue - a bug clicking on any upper cased suggestion. The in-memory search index that I use lower cases all values.

[1]: https://github.com/hadynz/obsidian-sidekick/releases/tag/1.0.4

**Comment by Quorafind** [comment]
![image](https://user-images.githubusercontent.com/13215013/153750773-ffab80c0-f8b4-4fef-a5f0-2d22f18c1939.png)

Yes, it fixes questions above. but a new error comes, sorry to tell you about this. 😂

**Comment by HEmile** [comment]
Some more stuff I'm seeing on 1.0.4:

<img width="349" alt="image" src="https://user-images.githubusercontent.com/1289165/153770282-d8e61a4a-6dc7-4510-b2c5-50bd7642e1f3.png">

Probably a + in the file title (and possibly other characters) isn't escaped properly in a regex

**Comment by hadynz** [comment]
I've done a bunch of tweaks that I am hoping 🤞  will auto-magically fix your issues in [1.0.5][1]. That is quite a wishful thought as I don't have enough debugging to determine the actual problem that you are running. 

If this doesn't fix your issue, I'll add more debugging messages to try and get to the bottom of the problem.

> Probably a + in the file title (and possibly other characters) isn't escaped properly in a regex

If you can share with me a list of example file titles that you think could be causing this problem I can test it quickly at my end.

[1]: https://github.com/hadynz/obsidian-sidekick/releases/tag/1.0.5

**Comment by Quorafind** [comment]
`[[2d3 Zettelkasten]] - 快速记录对于zettelkasten笔记的推动` don't know why here remains highlight : 
![image](https://user-images.githubusercontent.com/13215013/153858254-14bd1189-18d7-4c1c-a7db-5f9078e5a609.png)
![image](https://user-images.githubusercontent.com/13215013/153858281-40bf13e7-bf69-4b35-b1c6-ed97f6c3bcdb.png)
![image](https://user-images.githubusercontent.com/13215013/153858543-b990d3fa-7e94-44f2-87d6-126d10f83171.png)

**Comment by HEmile** [comment]
> I've done a bunch of tweaks that I am hoping 🤞 will auto-magically fix your issues in [1.0.5](https://github.com/hadynz/obsidian-sidekick/releases/tag/1.0.5). That is quite a wishful thought as I don't have enough debugging to determine the actual problem that you are running.
> 
> If this doesn't fix your issue, I'll add more debugging messages to try and get to the bottom of the problem.

Unfortunately not. The one that is causing it at least is "IDF++ Analyzing and Improving Integer Discrete Flows for Lossless Compression". I'm not sure if there are others... Probably those involving '-' too? I'm only seeing this error.

Still no highlighting at all for me, btw.

**Comment by HEmile** [comment]
If you are having trouble/are busy, I can try to debug it on my end. Won't be able to do that in the next couple days though, likely.

**Comment by hadynz** [comment]
Thanks for your help @HEmile. I am currently using a plugin to do search for me that uses Regex in its pipeline. I believe it is the one causing the issue that is being experienced here.

I am looking now to overhaul how searching and indexing works in the plugin to:
* Optimise for performance
* Use stemming
* Ignore [stop words][1]

I am hoping this will solve the issue being encountered in this thread.

Will update you once this change is complete. 

[1]: https://en.wikipedia.org/wiki/Stop_word

**Comment by hadynz** [comment]
I've just released [1.1.0][1] which is a rewrite for how search and indexing works. You can see details about the change in https://github.com/hadynz/obsidian-sidekick/pull/9.

Can you guys give this a try and let me know how it works at your end please.

[1]: https://github.com/hadynz/obsidian-sidekick/releases/tag/1.1.0

**Comment by HEmile** [comment]
Hey, thanks for the update! Unfortunately, I'm getting another error now
```
app.js:1 TypeError: Cannot read properties of undefined (reading 'replaceText')
    at eval (eval at <anonymous> (app.js:1), <anonymous>:59:67453)
    at Array.map (<anonymous>)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:59:67388)
    at Array.reduce (<anonymous>)
    at s.toSearchResults (eval at <anonymous> (app.js:1), <anonymous>:59:67342)
    at s.find (eval at <anonymous> (app.js:1), <anonymous>:59:67201)
    at e.r.ViewPlugin.fromClass.e.decorateView (eval at <anonymous> (app.js:1), <anonymous>:59:60063)
    at new e (eval at <anonymous> (app.js:1), <anonymous>:59:60798)
    at t.create (app.js:1)
    at t.update (app.js:1)
```

**Comment by HEmile** [comment]
More context: 
![image](https://user-images.githubusercontent.com/1289165/154259663-3a7382e1-13ec-4e2c-895c-377d6ed91159.png)
Ie it's getting a hit on 'acquir', but this is not a name/alias in my vault at all (indices['acquir']=undefined). I think something might be going wrong with the offset of where it's looking in the document.
![image](https://user-images.githubusercontent.com/1289165/154260197-3aa4d430-92e0-49fa-b958-5382158cb4ac.png)

**Comment by Quorafind** [comment]
And seems like it cannot suggest file name anymore? 
![image](https://user-images.githubusercontent.com/13215013/154265954-9bec2646-6bc5-4a22-a6f0-a658e99f0aa8.png)

**Comment by hadynz** [comment]
> Ie it's getting a hit on 'acquir', but this is not a name/alias in my vault at all (indices['acquir']=undefined). I think something might be going wrong with the offset of where it's looking in the document.

The plugin now is using a concept called "[stemming][1]" (the [Porter stemmer algorithm][3] to be exact) by default to try surface as many connections as possible. So it is possible that you have a tag or a page name that contains a word that stems to `acquir`. For example `acquire` or `acquiring`.

In #11 I made an update to skip any words that could be missing so you don't run into this problem anymore. Try out release  [1.1.1][1].

[1]: https://github.com/hadynz/obsidian-sidekick/releases/tag/1.1.1
[2]: https://en.wikipedia.org/wiki/Stemming
[3]: https://lunrjs.com/guides/core_concepts.html#stemming

**Comment by HEmile** [comment]
I see! It's definitely working for me now, up to some degree at least! I'll add a couple more issues now that I got it to work somewhat :)
