### ISSUE TITLE
Highlighting multiple words

### ISSUE THREAD

**Issue by mdbraber** [hadynz/obsidian-sidekick#10]
Love the idea of this plugin. I'm only getting highlight results for single words, is this expected or should also multiple worlds (e.g. "Test Note") be highlighted and suggested?

**Comment by hadynz** [comment]
Good call. 

Ideally the plugin should fine multiple words too. I did a quick test now and I can confirm that this not the case. So I'll mark this issue as a bug and will look into solving it.

I've just changed the searching engine recently, and looks like I need to do some further tweaking to it.

**Comment by mdbraber** [comment]
Thanks for considering. Happy to test any updates.

**Comment by hadynz** [comment]
This has now been fixed in [1.2.0][1]. If you can test and confirm that would be great 👍 

[1]: https://github.com/hadynz/obsidian-sidekick/releases/tag/1.2.0
