### ISSUE TITLE
Bug: Stemming (?) mishits

### ISSUE THREAD

**Issue by HEmile** [hadynz/obsidian-sidekick#12]
It is reporting many instances of search mishits, where hits could not be found in the index. They probably come from some stemming issue, although I wouldn't know what word it would be based on because I'm fairly sure I have no single-word titles/aliases like 'achieve', 'approximate', 'allow'... etc.

![image](https://user-images.githubusercontent.com/1289165/154455093-37bc08be-c4d8-4229-9311-dc86e96e4913.png)

In general, it might be a good idea to make the stemming optional, I'm getting a lot of hits now.

**Comment by hadynz** [comment]
At the end of the `console.warn` that is being printed, your entire Obsidian index should be included. Do you mind if you share that? It would be interesting to see what's there, and if we can see the source of these misses.

**Comment by HEmile** [comment]
I was just about to, haha. 
![image](https://user-images.githubusercontent.com/1289165/154456483-1e53eff6-cf04-495c-9fdd-3b0f8ab56699.png)
 
Here it shows some examples. It seems like the stemming cuts off some parts of the name rather arbitrarily?

**Comment by HEmile** [comment]
Example for paramet (which was not found)
![image](https://user-images.githubusercontent.com/1289165/154456825-fc6c27ed-979d-4371-8dd5-e51448b77b75.png)

**Comment by HEmile** [comment]
And similar for 'approx'
![image](https://user-images.githubusercontent.com/1289165/154457008-b95e8026-69c4-4356-bf94-862bff7fd5bc.png)

**Comment by hadynz** [comment]
Thanks for the screenshots. It will help me with recreating this problem at my end.

Stemming and the current lack of ability to highlight multiple words (#10) means that valid keywords that should be highlighted are not being highlighted. It doesn't explain why there are mishits though. But I have to go back to the drawing first to resolve the multiple words issue first.

Let me continue to mull over this. I'll keep you up to date with my progress.

**Comment by HEmile** [comment]
Thank you, it makes sense that it would give these issues if it cannot deal with multiple words, i suppose (I actually noticed that issue too in my vault).

**Comment by hadynz** [comment]
@HEmile Just released [1.2.0][1] which drops the concept of stemming and uses a very different algorithm for searching that I think is more appropriate for this plugin's use case (see #14 for details).

Give it a spin and let me know

[1]: https://github.com/hadynz/obsidian-sidekick/releases/tag/1.2.0

**Comment by HEmile** [comment]
No more errors, and the results look a lot better! Thank you :)

**Comment by HEmile** [comment]
I've played around with it a bit and it's super useful! With better performance I'm convinced it'll be a key part to my setup, thank you so much!
