### ISSUE TITLE
FR: Let users choose between multiple options

### ISSUE THREAD

**Issue by HEmile** [hadynz/obsidian-sidekick#15]
With aliases, it is possible to have multiple rewrites for the same hit. For example:
![image](https://user-images.githubusercontent.com/1289165/154658027-82a0979e-7d5a-49a2-80f1-f9587a472a16.png)

![image](https://user-images.githubusercontent.com/1289165/154658068-9009db2a-9977-4db9-9170-65ba46ac595c.png)

It would be very useful if the popup would be a list of such corrections, instead of suggesting only a single one

**Comment by hadynz** [comment]
Ha! This is excellent. Thanks for raising. It did cross my mind that this is possible. You've given a really good example of how so. Will definitely make sure that is implemented soon.

**Comment by hadynz** [comment]
This has now been implemented in [1.4.0][1]. If you can test that it works at your end, that would be great. 

[1]: https://github.com/hadynz/obsidian-sidekick/releases/tag/1.4.0

**Comment by HEmile** [comment]
It does look like it is able to disambiguate very well!! That's so useful!
