### ISSUE TITLE
Failed to load plugin obsidian-sidekick

### ISSUE THREAD

**Issue by Kolooooo** [hadynz/obsidian-sidekick#22]
<img width="256" alt="Snipaste_2022-02-23_11-15-34" src="https://user-images.githubusercontent.com/19557102/155256191-69f5c1da-39b9-4251-ad2f-0f9b04c3fd5f.png">

<img width="760" alt="image" src="https://user-images.githubusercontent.com/19557102/155256344-17e66acc-1f69-40e5-ad6a-2adb63b72a8d.png">

**Comment by hadynz** [comment]
I am unsure what this screenshot represents. 

Whilst this plugin is still in development (and not available to download via the Obsidian plugins repo), you are best off either manually downloading any of the latest [releases][1] or look at using BRAT (which I haven't tried myself, but know many are using for this use case).

[1]: https://github.com/hadynz/obsidian-sidekick/releases/

**Comment by Kolooooo** [comment]
I downloaded the file from github and added it to the obsidian plugin library, and when I opened the plugin from obsidian, it said "Failed to load plugin obsidian-sidekick", I really don't know which file to add to the obsidian plugin library. Please advise, thank you~
