### ISSUE TITLE
Bug: Parts of hierarchical tags are highlighted

### ISSUE THREAD

**Issue by HEmile** [hadynz/obsidian-sidekick#24]
https://user-images.githubusercontent.com/1289165/155120035-fcf15a23-3587-4965-830f-5e19c05e2bf1.mov

In this video, you can see that in the tag #source/paper, the "paper" part is highlighted, because I use the tag "#paper" somewhere in my vault. However, this shouldn't be a valid recommendation, as #source/paper is already a tag, just a different one. Apparently, the tokenizer considers the /paper as a separate thing, and not as part of the hierarchical tag #source/paper.

**Comment by hadynz** [comment]
This is now fixed in [1.4.2][1].

[1]: https://github.com/hadynz/obsidian-sidekick/releases/tag/1.4.2

**Comment by HEmile** [comment]
Yes, thanks!!
