### ISSUE TITLE
Plugin highlights everything

### ISSUE THREAD

**Issue by scriptor-dga** [hadynz/obsidian-sidekick#4]
I have a note called `[[Joseph]]`. Now the plugin highlights every word containing `jo` (also in the middle of the word). So I think that the plugin should only highlight entire words when they are contained in the titles of other notes.

![Obsidian_OfpdqYrzZh](https://user-images.githubusercontent.com/59956700/153748446-a10c1e98-deaa-4017-8754-d105a8214c7e.png)

**Comment by hadynz** [comment]
Yup, I noticed that too, and will fix.

However... can I confirm something: do you have an alias of `jo` defined for your `[[Joseph]]` note? That's the only way I can see why you are seeing the partial highlighting.

**Comment by scriptor-dga** [comment]
You're right, I did have an alias Jo. 😅 However, the highlighting stayed even after modifying the alias.

**Comment by hadynz** [comment]
> the highlighting stayed even after modifying the alias.

Good call. This could be a bug. The plugin should re-index all your files and tags after every change, and unhighlight in some cases. 

If you reload Obsidian or stop/start the plugin this should fix itself for now.

**Comment by shabegom** [comment]
+1 to only highlighting whole words, or having a setting to choose. I have a tag #q for questions, but it is now highlighting all the q across me vault. 

Very cool plugin!

**Comment by hadynz** [comment]
Just an update on this issue – I am looking to overhaul how searching works and actively working on the new solution. This solution will definitely be fixing this issue of partial highlights. 

Will share an update here when resolved. Appreciate your patience.

**Comment by HEmile** [comment]
It's also highlighting everywhere throughout my file, and it's not highlighting based on the correct searchwords (I checked in the code). The highlights should probably only work when surrounded with whitespace? And I think what I'm seeing is really a bug. Might have something to do with some offset in CM6.

![image](https://user-images.githubusercontent.com/1289165/154085041-cd019c64-e09b-4aaa-aaf4-73b716a33598.png)

**Comment by hadynz** [comment]
This should be fixed in [1.1.0][1]. If you can try and confirm that would be great.

[1]: https://github.com/hadynz/obsidian-sidekick/releases/tag/1.1.0

**Comment by HEmile** [comment]
Doesn't seem to be doing this anymore, no!
