### ISSUE TITLE
ignore yaml & codeblocks

### ISSUE THREAD

**Issue by chrisgrieser** [hadynz/obsidian-sidekick#5]
the plugin should not highlight things in yaml and code blocks, since text there has a different meaning and since markdown syntax is invalid there anyway.

<img width="363" alt="Screenshot 2022-02-13 11 39 04" src="https://user-images.githubusercontent.com/73286100/153749505-c0ef8ef8-409d-48b6-95c3-13f75d53a972.png">

**Comment by hadynz** [comment]
Agreed 👍 

Will implement shortly.

**Comment by hadynz** [comment]
This has now been implemented in [1.0.5][1] - for both code blocks and frontmatter. 

Thanks for suggesting this change.

If you can test and confirm it has been fixed that would be great.

[1]: https://github.com/hadynz/obsidian-sidekick/releases/tag/1.0.5

**Comment by chrisgrieser** [comment]
Code block is now ignored, but yaml frontmatter still shows suggestions
<img width="507" alt="Screenshot 2022-02-14 11 40 51" src="https://user-images.githubusercontent.com/73286100/153848891-9ef720da-9f72-430b-bcf9-81309fc0648b.png">

**Comment by hadynz** [comment]
@chrisgrieser I found a subsequent bug and fixed it in https://github.com/hadynz/obsidian-sidekick/pull/7 which was released [1.0.6][1]

[1]: https://github.com/hadynz/obsidian-sidekick/releases/tag/1.0.6
